CREATE DATABASE IF NOT EXISTS hm;
USE hm;
CREATE TABLE IF NOT EXISTS material(
id INT AUTO_INCREMENT PRIMARY KEY,
m_name VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS maden(
id INT AUTO_INCREMENT PRIMARY KEY,
price INT NOT NULL CHECK (price>0),
pic VARCHAR(255)
);
